# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uL2bBeRFpuwyVh6uIzTmo--y7WefyCUJ
"""

# ! pip install cohere
# ! pip install openai
# ! pip install git+https://github.com/openai/whisper.git -q

import whisper

model=whisper.load_model("medium")

!wget -O audio.mp3 http://www.moviesoundclips.net/movies1/batmanbegins/understanding.mp3

from IPython.display import Audio, display

display(Audio('audio.mp3', autoplay=True))

result=model.transcribe("audio.mp3")
print(result["text"])

######################################
display(Audio('style.wav', autoplay=True))

result=model.transcribe("style.wav")
print(result["text"])

######################################
display(Audio('Recording_Sunamdha1.wav', autoplay=True))

result=model.transcribe("Recording_Sunamdha1.wav")
print(result["text"])

